/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hu765630
 * Name: Sylvia Hurst
 * Teacher's Name: Mr. Yeung
 * Course: ICS
 * Start Date: November 6, 2019
 * End Date: November 6, 2019
 * Description: Super String Software
 */
public class FrmSuperStrings extends javax.swing.JFrame {

    /**
     * Creates new form FrmSuperStrings
     */
    public FrmSuperStrings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblText1 = new javax.swing.JLabel();
        lblText2 = new javax.swing.JLabel();
        lblText3 = new javax.swing.JLabel();
        lblText4 = new javax.swing.JLabel();
        lblText5 = new javax.swing.JLabel();
        lblText6 = new javax.swing.JLabel();
        lblText7 = new javax.swing.JLabel();
        lblOut1 = new javax.swing.JLabel();
        lblOut2 = new javax.swing.JLabel();
        lblOut3 = new javax.swing.JLabel();
        lblOut4 = new javax.swing.JLabel();
        lblOut5 = new javax.swing.JLabel();
        lblOut6 = new javax.swing.JLabel();
        lblOut7 = new javax.swing.JLabel();
        txt5b = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt4a = new javax.swing.JTextField();
        txt4b = new javax.swing.JTextField();
        txt5a = new javax.swing.JTextField();
        btn7 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUPER STRING SOFTWARE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 30, 250, 40);

        lblText1.setText("Enter a String. The program will output the number of characters in it.");
        getContentPane().add(lblText1);
        lblText1.setBounds(10, 100, 520, 30);

        lblText2.setText("Enter a String in lower case letters. The program will output it in all caps.");
        getContentPane().add(lblText2);
        lblText2.setBounds(10, 160, 520, 30);

        lblText3.setText("Enter a String. The program will output the character at the 4th spot.");
        getContentPane().add(lblText3);
        lblText3.setBounds(10, 220, 520, 30);

        lblText4.setText("Enter two Strings. The program will output whether or not they are identical.");
        getContentPane().add(lblText4);
        lblText4.setBounds(10, 280, 520, 30);

        lblText5.setText("Enter a String and a letter. The program will output whether or not the letter is in the String.");
        getContentPane().add(lblText5);
        lblText5.setBounds(10, 340, 530, 30);

        lblText6.setText("Enter a String that is at least 8 characters long. The program will output characters 4 to 6.");
        getContentPane().add(lblText6);
        lblText6.setBounds(10, 400, 530, 30);

        lblText7.setText("Enter a String with at least one 'a'. The program will output the String with all 'a's replaced with 'x's.");
        getContentPane().add(lblText7);
        lblText7.setBounds(10, 460, 540, 30);

        lblOut1.setText("...");
        getContentPane().add(lblOut1);
        lblOut1.setBounds(560, 100, 200, 30);

        lblOut2.setText("...");
        getContentPane().add(lblOut2);
        lblOut2.setBounds(560, 160, 200, 30);

        lblOut3.setText("...");
        getContentPane().add(lblOut3);
        lblOut3.setBounds(560, 220, 200, 30);

        lblOut4.setText("...");
        getContentPane().add(lblOut4);
        lblOut4.setBounds(560, 280, 200, 30);

        lblOut5.setText("...");
        getContentPane().add(lblOut5);
        lblOut5.setBounds(560, 340, 200, 30);

        lblOut6.setText("...");
        getContentPane().add(lblOut6);
        lblOut6.setBounds(560, 400, 200, 30);

        lblOut7.setText("...");
        getContentPane().add(lblOut7);
        lblOut7.setBounds(560, 460, 200, 30);
        getContentPane().add(txt5b);
        txt5b.setBounds(260, 370, 50, 30);
        getContentPane().add(txt1);
        txt1.setBounds(120, 130, 160, 30);
        getContentPane().add(txt2);
        txt2.setBounds(120, 190, 160, 30);
        getContentPane().add(txt3);
        txt3.setBounds(120, 250, 160, 30);
        getContentPane().add(txt6);
        txt6.setBounds(120, 430, 160, 30);
        getContentPane().add(txt7);
        txt7.setBounds(120, 490, 160, 30);
        getContentPane().add(txt4a);
        txt4a.setBounds(50, 310, 160, 30);
        getContentPane().add(txt4b);
        txt4b.setBounds(230, 310, 160, 30);
        getContentPane().add(txt5a);
        txt5a.setBounds(70, 370, 160, 30);

        btn7.setText("CLICK");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(420, 490, 80, 30);

        btn1.setText("CLICK");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(420, 130, 80, 30);

        btn2.setText("CLICK");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(420, 190, 80, 30);

        btn3.setText("CLICK");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(420, 250, 80, 30);

        btn4.setText("CLICK");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(420, 310, 80, 30);

        btn5.setText("CLICK");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(420, 370, 80, 30);

        btn6.setText("CLICK");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(420, 430, 80, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Variable declaration
    String input1, input2, input3, input4a, input4b, input5a, input5b, input6, input7;
    //Includes different variable types to store different types of data
    int result1;
    String result2, result3, result7;
    boolean result4, result5;
    char result6a, result6b, result6c;
    
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        //2: All caps
        
        //Getting user input from text boxes
        input2 = txt2.getText();
        
        //Using the String method to get the result
        result2 = input2.toUpperCase();
        
        //Displaying the result on the label
        lblOut2.setText(String.valueOf(result2));
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        //1: Length of String
        
        //Getting user input from text boxes
        input1 = txt1.getText();
        
        //Using the String method to get the result
        result1 = input1.length();
        
        //Displaying the result on the label
        lblOut1.setText(String.valueOf(result1));
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        //3: Index 4
        
        //Getting user input from text boxes
        input3 = txt3.getText();
        
        //Using the String method to get the result
        result3 = String.valueOf(input3.charAt(3));
        
        //Displaying the result on the label
        lblOut3.setText(String.valueOf(result3));
        
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        //4: Identical?
        
        //Getting user input from text boxes
        input4a = txt4a.getText();
        input4b = txt4b.getText();
        
        //Using the String method to get the result
        result4 = input4a.equals(input4b);
        
        //Displaying the result on the label
        lblOut4.setText(String.valueOf(result4));
        
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        //5: Letter in String?
        
        //Getting user input from text boxes
        input5a = txt5a.getText();
        input5b = txt5b.getText();
        
        //Using the String method to get the result
        result5 = input5a.contains(input5b);
        
        //Displaying the result on the label
        lblOut5.setText(String.valueOf(result5));
        
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        //6: Characters 4 to 6
        
        //Getting user input from text boxes
        input6 = txt6.getText();
        
        //Using the String method to get the result
        result6a = input6.charAt(3);
        result6b = input6.charAt(4);
        result6c = input6.charAt(5);
        
        //Displaying the result on the label
        lblOut6.setText(String.valueOf(result6a) + ", " + String.valueOf(result6b) + ", " + String.valueOf(result6c));
        
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        //7: Replace all 'a's with 'x's
        
        //Getting user input from text boxes
        input7 = txt7.getText();
        
        //Using the String method to get the result
        result7 = input7.replace("a", "x");
        
        //Displaying the result on the label
        lblOut7.setText(String.valueOf(result7));
        
    }//GEN-LAST:event_btn7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSuperStrings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSuperStrings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSuperStrings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSuperStrings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSuperStrings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOut1;
    private javax.swing.JLabel lblOut2;
    private javax.swing.JLabel lblOut3;
    private javax.swing.JLabel lblOut4;
    private javax.swing.JLabel lblOut5;
    private javax.swing.JLabel lblOut6;
    private javax.swing.JLabel lblOut7;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblText2;
    private javax.swing.JLabel lblText3;
    private javax.swing.JLabel lblText4;
    private javax.swing.JLabel lblText5;
    private javax.swing.JLabel lblText6;
    private javax.swing.JLabel lblText7;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4a;
    private javax.swing.JTextField txt4b;
    private javax.swing.JTextField txt5a;
    private javax.swing.JTextField txt5b;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    // End of variables declaration//GEN-END:variables
}
