/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hu765630
 * Name: Sylvia Hurst
 * Teacher's Name: Mr. Yeung
 * Course: ICS
 * Start Date: October 7, 2019
 * End Date: October 8, 2019
 * Description: Using a switch statement to display a randomly generated positive message.
 */
public class FrmPositivePractice extends javax.swing.JFrame {

    /**
     * Creates new form FrmPositivePractice
     */
    public FrmPositivePractice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnClick = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnClick.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btnClick.setForeground(new java.awt.Color(0, 204, 51));
        btnClick.setText("CLICK");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });
        getContentPane().add(btnClick);
        btnClick.setBounds(310, 80, 120, 40);

        lblMessage.setFont(new java.awt.Font("Sylfaen", 2, 18)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 204, 51));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMessage);
        lblMessage.setBounds(10, 130, 740, 90);

        lblTitle.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 204, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Positive Practice");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(230, 10, 280, 33);

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Click the button below to generate a positive message!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 44, 450, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        //Variable declaration
        int random;
    
    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        
        //Determining random value
        random = (int)Math.round(Math.random()*8+1);
        
        //Switch statement to determine output to the lblMessage label
        switch (random) {
            case 1:
                lblMessage.setText("Don't waste time looking at the past. You're not going that way.");
                break;
            case 2:
                lblMessage.setText("Attitude is a little thing that makes a big difference.");
                break;
            case 3:
                lblMessage.setText("Keep your face to the sunshine and you cannot see a shadow.");
                break;
            case 4:
                lblMessage.setText("The worst times can be the best if you think with positive energy.");
                break;
            case 5:
                lblMessage.setText("Strength grows in the moment when you think you can't go on but you keep going anyway.");
                break;
            case 6:
                lblMessage.setText("Don't see problems in life as stop signs, see them as guidelines.");
                break;
            case 7:
                lblMessage.setText("Difficult roads often lead to beautiful destinations.");
                break;
            case 8:
                lblMessage.setText("You may have to fight a battle more than once to win it.");
                break;
        }
        
    }//GEN-LAST:event_btnClickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPositivePractice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPositivePractice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPositivePractice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPositivePractice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPositivePractice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
