/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hu765630
 * Name: Sylvia Hurst
 * Teacher's Name: Mr. Yeung
 * Course: ICS
 * Start Date: September 23, 2019
 * End Date: September 25, 2019
 * Description: A multiple choice quiz that incorporates switch statements, if statements, boolean logic operators to account for upper case or lower case letter inputs, score-keeping variables, and percentage.
 */
public class FrmMultipleChoice extends javax.swing.JFrame {

    /**
     * Creates new form FrmMultipleChoice
     */
    public FrmMultipleChoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAnswer = new javax.swing.JTextField();
        lblQuestion = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblYourAnswer = new javax.swing.JLabel();
        lblA = new javax.swing.JLabel();
        lblB = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        lblD = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        lblCorrectValue = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();
        lblCorrect = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblPercent = new javax.swing.JLabel();
        lblFeedback = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtAnswer.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtAnswer.setForeground(new java.awt.Color(0, 0, 255));
        txtAnswer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnswer);
        txtAnswer.setBounds(190, 250, 70, 50);

        lblQuestion.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(0, 0, 255));
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblQuestion);
        lblQuestion.setBounds(10, 70, 440, 40);

        lblTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Cat Quiz");
        getContentPane().add(lblTitle);
        lblTitle.setBounds(120, 10, 210, 50);

        lblYourAnswer.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblYourAnswer.setForeground(new java.awt.Color(0, 0, 255));
        lblYourAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblYourAnswer.setText("Your Answer:");
        getContentPane().add(lblYourAnswer);
        lblYourAnswer.setBounds(50, 260, 110, 30);

        lblA.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblA.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(lblA);
        lblA.setBounds(30, 120, 180, 40);

        lblB.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblB.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(lblB);
        lblB.setBounds(30, 180, 180, 40);

        lblC.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblC.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(lblC);
        lblC.setBounds(240, 120, 200, 40);

        lblD.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lblD.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(lblD);
        lblD.setBounds(240, 180, 200, 40);

        btnNext.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(0, 0, 255));
        btnNext.setText("BEGIN");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext);
        btnNext.setBounds(300, 250, 110, 50);

        lblCorrectValue.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCorrectValue.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(lblCorrectValue);
        lblCorrectValue.setBounds(280, 340, 50, 30);

        lblIncorrectValue.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblIncorrectValue.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(lblIncorrectValue);
        lblIncorrectValue.setBounds(280, 380, 50, 30);

        lblPercentValue.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblPercentValue.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(lblPercentValue);
        lblPercentValue.setBounds(280, 420, 50, 30);

        lblCorrect.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblCorrect.setForeground(new java.awt.Color(0, 0, 255));
        lblCorrect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblCorrect);
        lblCorrect.setBounds(100, 334, 120, 40);

        lblIncorrect.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblIncorrect.setForeground(new java.awt.Color(0, 0, 255));
        lblIncorrect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblIncorrect);
        lblIncorrect.setBounds(98, 374, 120, 40);

        lblPercent.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblPercent.setForeground(new java.awt.Color(0, 0, 255));
        lblPercent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblPercent);
        lblPercent.setBounds(78, 414, 160, 40);

        lblFeedback.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblFeedback.setForeground(new java.awt.Color(0, 0, 255));
        lblFeedback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblFeedback);
        lblFeedback.setBounds(190, 330, 70, 30);

        lblScore.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        lblScore.setForeground(new java.awt.Color(0, 0, 255));
        lblScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblScore);
        lblScore.setBounds(190, 380, 70, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //declaring variables
    int presses = 0;
    int correct = 0;
    int incorrect = 0;
    double percent = 0;
    String a1;
    String a2;
    String a3;
    String a4;
    String a5;
    
    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
        //Questions:
        //What is a male cat called? A: Tom, B: Bob, C: Terry, D: Jerry; (A)
        //What is a female cat called? A: Molly, B: Empress, C: Queen, D: Sally; (C)
        //What is a group of cats called? A: Cluster, B: Clowder, C: Clamour, D: Catastrophe; (B)
        //How many kittens does a mother usually have in one litter? A: Over 10, B: 6-8, C: 3-5, D: Just 1; (C)
        //Which ancient civilization worshipped cats for their help in hunting mice? A: Rome, B: Greece, C: Aztecs, D: Egypt; (D)
        
        //Determining how many times the button has been pressed so that it can display the correct question
        presses = presses + 1;
        
        switch (presses) {
            case 1:
                //Changing button to read "NEXT" for the first 4 questions
                btnNext.setText("NEXT");
                //Question 1
                lblQuestion.setText("What is a male cat called?");
                lblA.setText("A: Tom");
                lblB.setText("B: Bob");
                lblC.setText("C: Terry");
                lblD.setText("D: Jerry");
                break;
            case 2:
                //Taking input from Question 1 and emptying text box
                a1 = (txtAnswer.getText());
                txtAnswer.setText("");
                
                //Determining whether the user got the answer right or wrong
                if ("a".equals(a1) || "A".equals(a1))
                {
                    correct = correct + 1;
                    lblFeedback.setText("Correct!");
                    lblScore.setText("Score: " + correct);
                }
                else
                {
                    incorrect = incorrect + 1;
                    lblFeedback.setText("Incorrect!");
                }
                
                //Question 2
                lblQuestion.setText("What is a female cat called?");
                lblA.setText("A: Molly");
                lblB.setText("B: Empress");
                lblC.setText("C: Queen");
                lblD.setText("D: Sally");
                break;
            case 3:
                //Taking input from Question 2 and emptying text box
                a2 = (txtAnswer.getText());
                txtAnswer.setText("");
                
                //Determining whether the user got the answer right or wrong
                if ("c".equals(a2) || "C".equals(a2))
                {
                    correct = correct + 1;
                    lblFeedback.setText("Correct!");
                    lblScore.setText("Score: " + correct);
                }
                else
                {
                    incorrect = incorrect + 1;
                    lblFeedback.setText("Incorrect!");
                }
                
                //Question 3
                lblQuestion.setText("What is a group of cats called?");
                lblA.setText("A: Cluster");
                lblB.setText("B: Clowder");
                lblC.setText("C: Clamour");
                lblD.setText("D: Catastrophe");
                break;
            case 4:
                //Taking input from Question 3 and emptying text box
                a3 = (txtAnswer.getText());
                txtAnswer.setText("");
                
                //Determining whether the user got the answer right or wrong
                if ("b".equals(a3) || "B".equals(a3))
                {
                    correct = correct + 1;
                    lblFeedback.setText("Correct!");
                    lblScore.setText("Score: " + correct);
                }
                else
                {
                    incorrect = incorrect + 1;
                    lblFeedback.setText("Incorrect!");
                }
                
                //Question 4
                lblQuestion.setText("How many kittens does a mother usually have at once?");
                lblA.setText("A: Over 10");
                lblB.setText("B: 6-8");
                lblC.setText("C: 3-5");
                lblD.setText("D: Just 1");
                break;
            case 5:
                //Setting button to read "FINISH" since this is the last question
                btnNext.setText("FINISH");

                //Taking input from Question 4 and emptying text box
                a4 = (txtAnswer.getText());
                txtAnswer.setText("");
                
                //Determining whether the user got the answer right or wrong
                if ("c".equals(a4) || "C".equals(a4))
                {
                    correct = correct + 1;
                    lblFeedback.setText("Correct!");
                    lblScore.setText("Score: " + correct);
                }
                else
                {
                    incorrect = incorrect + 1;
                    lblFeedback.setText("Incorrect!");
                }
                
                //Question 5
                lblQuestion.setText("Which ancient civilization worshipped cats?");
                lblA.setText("A: Rome");
                lblB.setText("B: Greece");
                lblC.setText("C: Aztecs");
                lblD.setText("D: Egypt");
                break;
            case 6:
                //Emptying temporary score/feedback variables so that final results can be displayed instead
                lblFeedback.setText("");
                lblScore.setText("");

                //Taking input from Question 5 and emptying text box
                a5 = (txtAnswer.getText());
                txtAnswer.setText("");
                
                //Determining whether the user got the answer right or wrong
                if ("d".equals(a5) || "D".equals(a5))
                {
                    correct = correct + 1;
                }
                else
                {
                    incorrect = incorrect + 1;
                }
                
                //Results calculation
                percent = (double)correct / 5.0 * 100;
                
                //Rounding percent to one decimal place
                percent = percent * 10;
                percent = Math.round(percent);
                percent = percent / 10;
                
                //Setting all the labels to display the results
                lblCorrect.setText("Correct:");
                lblIncorrect.setText("Incorrect:");
                lblPercent.setText("% of correct answers:");
                lblCorrectValue.setText(String.valueOf(correct));
                lblIncorrectValue.setText(String.valueOf(incorrect));
                lblPercentValue.setText(String.valueOf(percent));
                
                break;
        }
        
        
        
        
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMultipleChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMultipleChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMultipleChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMultipleChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMultipleChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblD;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYourAnswer;
    private javax.swing.JTextField txtAnswer;
    // End of variables declaration//GEN-END:variables
}
